config/routes.rb
SampleApp::Application.routes.draw do
    
  
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  
  root              :to => "pages#home"  #replaces get "pages/home" line
  
  match '/about',   :to => 'pages#about'  #this creates a named route and thus allows us to do home_path or home_url to link to this page
  match '/contact', :to => 'pages#contact'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout',  :to => 'sessions#destroy'
  
  
  

end

app/models/user.rb
# == Schema Information
# Schema version: 20110510014545
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#

require 'digest'
class User < ActiveRecord::Base
  attr_accessor   :password   #We decided to use an encrypted password instead of adding a column for password. This is a virtual attribute created by attr_accessor...it creates the getter/setter attributes that will allow us to manipulate password and do thing like User.password = something etc
  attr_accessible :name, :email, :password, :password_confirmation  #It's a good practise to tell Rails which attributes of the model will be modified by users, thus the attr_accessible
  
  email_regex =/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  #validates :name, :presence => true
  validates :name,  :presence => true ,
                    :length   => {:maximum => 50 }
  
  validates :email, :presence => true,
                    :format => { :with => email_regex },
                    #:uniqueness => true
                    :uniqueness => { :case_sensitive => false }
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40 }
  
  before_save :encrypt_password
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  #the following method is a User class method and can be also written as User.authenticate or self.authenticate() or
  #within the class << self block
  
  class << self
    def authenticate(email, submitted_password)
        user = User.find_by_email(email)
        #refactoring of next to lines to 3rd line
        #return nil if user.nil?
        #return user if user.has_password?(submitted_password)
        (user && user.has_password?(submitted_password)) ? user : nil
    end
    
    def authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil   #return user if user exists AND user.salt matches cookie_salt, else return nil
    end
  end
  
  private
  
    def encrypt_password
      self.salt = make_salt if new_record?  
      self.encrypted_password = encrypt(password)  #ruby knows we meant encrypt(self.password), which is more verbose...but both are good
    end
    
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end
  
  def about
    @title = "About"
  end
  
  def help
    @title = "Help"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @title = "Sign in"
  end
  
  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?    
      flash.now[:error] = "Invalid email/password combination"
      @title = "Sign in"
      render 'new'
    else
      sign_in user
      redirect_to user # same as 'redirect_to user_path(user)'
    end  
  end
  
  
  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  
  def show
    @user = User.find(params[:id])
    @title = @user.name 
  end
  
  def new
    @user = User.new
    @title = "Sign up"
  end
  
  def create
      @user = User.new(params[:user])
      if @user.save
        #flash[:success] = "Welcome to the Sample App!"
        sign_in @user  #user is signed in when they sign up/Some apps have users sign in after sign up as a separate action
        redirect_to @user, :flash => {:success => "Welcome to the Sample App!"}
      else
        @title = "Sign up"
        render 'new'
      end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Return a title on a per-page basis
  def title
    base_title = "Ruby on Rails Tutorial Sample App"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  
  def logo
    image_tag("logo.png", :alt => "Sample App", :class => "round")
  end
  
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    current_user = user
  end
  
  #the followig two methods are a setter and getter methods, the same as attr_accessor used in the User model
  #the accessor is defined explicitly here
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
      # @current_user || user_from_remember_token  #or @current = @current_user || user_from_remember_token
      #because we are going to be using @current_user for many things, we don't want to hit the database everytime as the line above would do.
      #so the solution is the flowing line which would check if @current_user is nil it would assign it 'user_from_remember_token' which will hit the database, but the second time it's requested is will just return it without hiting the database again
       @current_user ||= user_from_remember_token      #or  @current = @current_user ||= user_from_remember_token
  end
  
  def signed_in?
    !current_user.nil?   #bolean signed_in? is true when current_user is NOT nil
  end
  
  def sign_out
    cookies.delete(:remember_token)
    #self.current_user = nil     #We first had to used the full "self.current_user = nil" because for some reason "current_user = nil" did not work with the tests
    current_user = nil        #we can now use this without (self) after we reused the sign_in method in spec_helper...see comments in spec_helper
  end
    
  private
  
    def user_from_remember_token
      User.authenticate_with_salt(*remember_token) 
      #by adding the * we are unwrapping [user.id, user.salt],
      #if method add() takes two arguments add(1,2), trying add([1,2]) would generate an error,
      #but is we do add(*[1,2]), the * would unrapp one layer and add the element in the list, same as above     
    end
    
    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(@user.email.downcase, :alt => user.name,
                                             :class => "gravatar",
                                             :gravatar => options)
  end
  
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "News", 'http://news.railstutorial.org/' %></li>
      <li><%= link_to "Rails Tutorial", 'http://railstutorial.org/' %></li>
    </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <% if signed_in? %>
        <li><%= link_to "Profile", current_user %></li>   
        <!-- Above line is the same as: link_to "Profile", user_path(current_user) -->
      <% end %>
      <li><%= link_to "Help", help_path %></li>
      <% if signed_in? %>
        <li><%= link_to "Sign out", signout_path %></li>
      <% else %>
      <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
 <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= stylesheet_link_tag 'custom', :media =>  'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html  >
<html>
  <head>
	  <title><%= title %></title>
	  <%= csrf_meta_tag %>
	  <%= render 'layouts/stylesheets'%>
	</head>

  <body>
    <div class="container">
      <%= render 'layouts/header'%>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer'%>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>

</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development with <a     
  href="http://rubyonrails.org/">Ruby on Rails</a>.  This is the sample application for the tutorial.
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the 
  <a href="http://railstutorial.org/feedback">feedback page</a>
  sample application.
</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
  Get help on Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  To get help on this sample app, see the
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.  
</p>

app/views/pages/home.html.erb
<h1>Sample Application</h1>
<p>
  This is the home page for the 
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error")%>
      prohibited this user from being saved:
    </h2>
    <p> There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>     
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="filed">
    <%= f.label :name %></br>
    <%= f.text_field :name %>
  </div>
  
  <div class="filed">
    <%= f.label :email %></br>
    <%= f.text_field :email %>
  </div>
  
  <div class="filed">
    <%= f.label :password %></br>
    <%= f.password_field :password %>
  </div>
  
  <div class="filed">
    <%= f.label :password_confirmation, "Confirmation" %></br>
    <%= f.password_field :password_confirmation %>
  </div>
  
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>
  

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br/>
      <strong>URL</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>